INSERT INTO `cms3_hierarchy_types` VALUES 
('2', 'content', 'i18n::hierarchy-type-content-page', ''), 
('4', 'users', 'i18n::hierarchy-type-users-user', 'user'), 
('5', 'catalog', 'i18n::hierarchy-type-catalog-category', 'category'), 
('6', 'catalog', 'i18n::hierarchy-type-catalog-object', 'object'), 
('8', 'users', 'i18n::hierarchy-type-users-users', 'users'), 
('9', 'news', 'i18n::hierarchy-type-news-rubric', 'rubric'), 
('10', 'news', 'i18n::hierarchy-type-news-item', 'item'), 
('11', 'news', 'i18n::hierarchy-type-news-subject', 'subject'), 
('12', 'vote', 'i18n::hierarchy-type-vote-poll', 'poll'), 
('13', 'vote', 'i18n::hierarchy-type-vote-poll_item', 'poll_item'), 
('18', 'forum', 'i18n::hierarchy-type-forum-conf', 'conf'), 
('19', 'forum', 'i18n::hierarchy-type-forum-topic', 'topic'), 
('20', 'forum', 'i18n::hierarchy-type-forum-message', 'message'), 
('21', 'comments', 'i18n::hierarchy-type-comments-comment', 'comment'), 
('22', 'updatesrv', 'i18n::hierarchy-type-updatesrv-license', 'license'), 
('23', 'updatesrv', 'i18n::hierarchy-type-updatesrv-license_type', 'license_type'), 
('24', 'banners', 'i18n::hierarchy-type-banners-banner', 'banner'), 
('25', 'banners', 'i18n::hierarchy-type-banners-place', 'place'), 
('26', 'dispatches', 'i18n::hierarchy-type-dispatches-dispatch', 'dispatch'), 
('27', 'dispatches', 'i18n::hierarchy-type-dispatches-release', 'release'), 
('28', 'dispatches', 'i18n::hierarchy-type-dispatches-message', 'message'), 
('29', 'dispatches', 'i18n::hierarchy-type-dispatches-subscriber', 'subscriber'), 
('31', 'catalog', 'i18n::hierarchy-type-catalog-question', 'question'), 
('32', 'catalog', 'i18n::hierarchy-type-catalog-answer', 'answer'), 
('33', 'users', 'i18n::hierarchy-type-users-author', 'author'), 
('34', 'content', 'i18n::hierarchy-type-content-ticket', 'ticket'), 
('35', 'photoalbum', 'i18n::hierarchy-type-photoalbum-album', 'album'), 
('36', 'photoalbum', 'i18n::hierarchy-type-photoalbum-photo', 'photo'), 
('37', 'faq', 'i18n::hierarchy-type-faq-project', 'project'), 
('38', 'faq', 'i18n::hierarchy-type-faq-category', 'category'), 
('39', 'faq', 'i18n::hierarchy-type-faq-question', 'question'), 
('40', 'filemanager', 'i18n::hierarchy-type-filemanager-shared_file', 'shared_file'), 
('46', 'blogs', 'i18n::hierarchy-type-blogs-blog', 'blog'), 
('47', 'blogs', 'i18n::hierarchy-type-blogs-blog_privacy', 'blog_privacy'), 
('48', 'blogs', 'i18n::hierarchy-type-blogs-blog_comment', 'blog_comment'), 
('49', 'blogs', 'i18n::hierarchy-type-blogs-blog_message', 'blog_message'), 
('52', 'webforms', 'i18n::hierarchy-type-webforms-form', 'form'), 
('53', 'webforms', 'i18n::hierarchy-type-webforms-template', 'template'), 
('54', 'webforms', 'i18n::hierarchy-type-webforms-address', 'address'), 
('55', 'users', 'i18n::hierarchy-type-users-avatar', 'avatar'), 
('57', 'blogs20', 'i18n::hierarchy-type-blogs-blog', 'blog'), 
('58', 'blogs20', 'i18n::hierarchy-type-blogs20-comment', 'comment'), 
('59', 'blogs20', 'i18n::hierarchy-type-blogs20-post', 'post'), 
('61', 'webforms', 'i18n::hierarchy-type-webforms-page', 'page'), 
('62', 'emarket', 'Заказ в магазине', 'order'), 
('63', 'emarket', 'Статус заказа', 'order_status'), 
('64', 'emarket', 'Склад', 'store'), 
('65', 'emarket', 'Статус оплаты', 'order_payment_status'), 
('66', 'emarket', 'Статус доставки', 'order_delivery_status'), 
('67', 'emarket', 'Наименование в заказе', 'order_item'), 
('68', 'emarket', 'Опция товара', 'item_option'), 
('69', 'emarket', 'Незарегистрированный покупатель', 'customer'), 
('70', 'emarket', 'Скидка', 'discount'), 
('71', 'emarket', 'Модификатор цены скидки', 'discount_modificator'), 
('72', 'emarket', 'Правило скидки', 'discount_rule'), 
('73', 'emarket', 'Тип скидки', 'discount_type'), 
('74', 'emarket', 'Тип модификатора скидки', 'discount_modificator_type'), 
('75', 'emarket', 'Тип правила скидки', 'discount_rule_type'), 
('76', 'emarket', 'Валюта', 'currency'), 
('77', 'emarket', 'Способ доставки', 'delivery'), 
('78', 'emarket', 'Тип доставки', 'delivery_type'), 
('79', 'emarket', 'Тип способа доставки', 'payment_type'), 
('80', 'emarket', 'Способ оплаты', 'payment'), 
('81', 'emarket', 'i18n::hierarchy-type-eshop-address', 'delivery_address'), 
('82', 'exchange', 'Обмен данными: Экспорт', 'export'), 
('83', 'exchange', 'Обмен данными: Импорт', 'import'), 
('84', 'emarket', 'Тип товара', 'item_type'), 
('85', 'emarket', 'Юридическое лицо', 'legal_person'), 
('86', 'social_networks', 'Социальные сети', 'network'), 
('87', 'social_networks', 'Вконтакте', 'vkontakte')